require("items.apple")
require("items.menus")
local spaces = require("items.spaces")
local front_app = require("items.front_app")
require("items.calendar")
require("items.widgets")
require("items.media")
spaces.start(front_app)
